# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ur_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur_manipulator_controller:
  ros__parameters:
    joints:
      - Revolute_20
      - Revolute_11
      - Revolute_7
      - Revolute_12
      - Revolute_13
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joint: Revolute_14
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

